Models/FaultLog.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace FaultReportingSystem.Models
{
    public class FaultLog
    {
        [Key]
        [DisplayName("Fault Log Id")]
        public int LogId { get; set; }

        [DisplayName("Date & Time")]
        public DateTime DateTime { get; set; }

        [StringLength(500)]
        [DisplayName("Action Performed")]
        public string Action { get; set; }

        [DisplayName("Developer Id")]
        public int? DeveloperId { get; set; }
        public Developer? Developer { get; set; }

        [DisplayName("Fault Id")]
        public int? FaultId { get; set; }
        public Fault? Fault { get; set; }
    }
}

Controllers/FaultLogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FaultReportingSystem.Data;
using FaultReportingSystem.Models;

namespace FaultReportingSystem.Controllers
{
    public class FaultLogsController : BaseController
    {
        private readonly ApplicationDbContext _context;

        public FaultLogsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult ViewFaultLogs(int faultId)
        {
            PopulateDropdowns();
            var faultWithLogs = _context.Faults.Include(f => f.Customer)
                .Include(f => f.Developer)
                .Include(f => f.HelpDesk)
                .Include(f => f.SoftwareProduct)
                .Include(f => f.FaultLogs)
                .FirstOrDefault(f => f.FaultId == faultId);
            if (faultWithLogs == null)
            {
                return NotFound();
            }

            return View("ViewFaultLogs", faultWithLogs);
        }

        public async Task<IActionResult> Index()
        {
            PopulateDropdowns();
            var applicationDbContext = _context.FaultLogs.Include(f => f.Developer).Include(f => f.Fault);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            PopulateDropdowns();
            if (id == null || _context.FaultLogs == null)
            {
                return NotFound();
            }

            var faultLog = await _context.FaultLogs
                .Include(f => f.Developer)
                .Include(f => f.Fault)
                .FirstOrDefaultAsync(m => m.LogId == id);
            if (faultLog == null)
            {
                return NotFound();
            }

            return View(faultLog);
        }

        public IActionResult Create(int faultId, int developerId)
        {
            PopulateDropdowns();
            ViewData["DeveloperId"] = new SelectList(_context.Developers, "DeveloperId", "DeveloperId");
            ViewData["FaultId"] = new SelectList(_context.Faults, "FaultId", "FaultId");
            ViewData["SelectedFaultId"] = faultId;
            ViewData["SelectedDeveloperId"] = developerId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LogId,DateTime,Action,DeveloperId,FaultId")] FaultLog faultLog)
        {
            PopulateDropdowns();
            if (ModelState.IsValid)
            {
                _context.Add(faultLog);
                await _context.SaveChangesAsync();
                TempData["FaultLogAddedMessage"] = "New Fault Log Added!";
                return RedirectToAction("ViewFaultLogs", new { faultId = faultLog.FaultId });
            }
            ViewData["DeveloperId"] = new SelectList(_context.Developers, "DeveloperId", "DeveloperId", faultLog.DeveloperId);
            ViewData["FaultId"] = new SelectList(_context.Faults, "FaultId", "FaultId", faultLog.FaultId);
            return View(faultLog);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            PopulateDropdowns();
            if (id == null || _context.FaultLogs == null)
            {
                return NotFound();
            }

            var faultLog = await _context.FaultLogs.FindAsync(id);
            if (faultLog == null)
            {
                return NotFound();
            }
            ViewData["DeveloperId"] = new SelectList(_context.Developers, "DeveloperId", "DeveloperId", faultLog.DeveloperId);
            ViewData["FaultId"] = new SelectList(_context.Faults, "FaultId", "FaultId", faultLog.FaultId);
            return View(faultLog);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LogId,DateTime,Action,DeveloperId,FaultId")] FaultLog faultLog)
        {
            PopulateDropdowns();
            if (id != faultLog.LogId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                PopulateDropdowns();
                try
                {
                    _context.Update(faultLog);
                    await _context.SaveChangesAsync();
                    TempData["FaultLogUpdatedMessage"] = "Fault Log Updated Successfully!";                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FaultLogExists(faultLog.LogId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("ViewFaultLogs", new { faultId = faultLog.FaultId });
            }
            ViewData["DeveloperId"] = new SelectList(_context.Developers, "DeveloperId", "DeveloperId", faultLog.DeveloperId);
            ViewData["FaultId"] = new SelectList(_context.Faults, "FaultId", "FaultId", faultLog.FaultId);
            return View(faultLog);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            PopulateDropdowns();
            if (id == null || _context.FaultLogs == null)
            {
                return NotFound();
            }

            var faultLog = await _context.FaultLogs
                .Include(f => f.Developer)
                .Include(f => f.Fault)
                .FirstOrDefaultAsync(m => m.LogId == id);
            if (faultLog == null)
            {
                return NotFound();
            }

            return View(faultLog);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            PopulateDropdowns();
            if (_context.FaultLogs == null)
            {
                return Problem("Fault Log 'ApplicationDbContext.FaultLogs' not found.");
            }
            var faultLog = await _context.FaultLogs.FindAsync(id);
            if (faultLog != null)
            {
                _context.FaultLogs.Remove(faultLog);
            }            
            await _context.SaveChangesAsync();
            TempData["FaultLogDeletedMessage"] = "Fault Log Deleted Successfully!";
            return RedirectToAction("ViewFaultLogs", new { faultId = faultLog.FaultId });
        }

        private bool FaultLogExists(int id)
        {
          return (_context.FaultLogs?.Any(e => e.LogId == id)).GetValueOrDefault();
        }

        private void PopulateDropdowns()
        {
            var developers = _context.Developers.Select(d => new
            {
                d.DeveloperId,
                DeveloperFullNameWithEmail = $"{d.DeveloperFirstName} {d.DeveloperLastName} ({d.DeveloperEmail})"
            }).ToList();
            var customers = _context.Customers.Select(c => new
            {
                c.CustomerId,
                CustomerFullNameWithEmail = $"{c.CustomerFirstName} {c.CustomerLastName} ({c.CustomerEmail})"
            }).ToList();
            var helpdesks = _context.HelpDesks.Select(h => new
            {
                h.HelpDeskId,
                HelpDeskFullNameWithEmail = $"{h.HelpDeskFirstName} {h.HelpDeskLastName} ({h.HelpDeskEmail})"
            }).ToList();
            var softwareproducts = _context.SoftwareProducts.Select(s => new
            {
                s.SoftwareProductId,
                SoftwareProductIdWithName = $"{s.ProductName} (Product Id: {s.SoftwareProductId})"
            }).ToList();

            ViewBag.Developers = new SelectList(developers, "DeveloperId", "DeveloperFullNameWithEmail");
            ViewBag.Customers = new SelectList(customers, "CustomerId", "CustomerFullNameWithEmail");
            ViewBag.HelpDesks = new SelectList(helpdesks, "HelpDeskId", "HelpDeskFullNameWithEmail");
            ViewBag.SoftwareProducts = new SelectList(softwareproducts, "SoftwareProductId", "SoftwareProductIdWithName");
        }
    }
}

Views/FaultLogs/Create.cshtml
@model FaultReportingSystem.Models.FaultLog

@{
    ViewData["Title"] = "Add Fault Log";
}
<h1>Add Fault Log</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DateTime" class="control-label"></label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Action" class="control-label"></label>
                <input asp-for="Action" class="form-control" />
                <span asp-validation-for="Action" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeveloperId" class="control-label"></label>
                <select asp-for="DeveloperId" class="form-control form-select" asp-items="ViewBag.Developers"></select>
                <span asp-validation-for="DeveloperId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FaultId" class="control-label">Fault Id</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><strong class="fs-6">F-</strong></span>
                    <select asp-for="FaultId" class="form-control form-select" asp-items="ViewBag.FaultId"></select>
                </div>
            </div><br />
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-outline-primary" />
                <a asp-action="ViewFaultLogs" asp-route-faultId="@ViewData["SelectedFaultId"]" class="btn btn-outline-secondary">Back To Fault Logs</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/FaultLogs/Delete.cshtml
@model FaultReportingSystem.Models.FaultLog

@{
    ViewData["Title"] = "Delete Fault Log";
}
<h1>Delete Fault Log</h1>

<h3>Are you sure you want to delete this Fault Log?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Action)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Action)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Developer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Developer.DeveloperFullNameWithEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fault)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fault.Problem)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="LogId" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" />
        <a asp-controller="FaultLogs" asp-action="ViewFaultLogs" asp-route-faultId="@Model.FaultId" class="btn btn-outline-secondary">Back To Fault Logs</a>
    </form>
</div>

Views/FaultLogs/Details.cshtml
@model FaultReportingSystem.Models.FaultLog

@{
    ViewData["Title"] = "Details";
}
<h1>Fault Log Details</h1>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Action)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Action)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Developer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Developer.DeveloperId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fault)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fault.FaultId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.LogId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/FaultLogs/Edit.cshtml
@model FaultReportingSystem.Models.FaultLog

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Fault Log</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LogId" />
            <div class="form-group">
                <label asp-for="DateTime" class="control-label"></label>
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Action" class="control-label"></label>
                <input asp-for="Action" class="form-control" />
                <span asp-validation-for="Action" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeveloperId" class="control-label"></label>
                <select asp-for="DeveloperId" class="form-control" asp-items="ViewBag.Developers"></select>
                <span asp-validation-for="DeveloperId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FaultId" class="control-label">Fault Id</label>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><strong class="fs-6">F-</strong></span>
                    <select asp-for="FaultId" class="form-control form-select" asp-items="ViewBag.FaultId"></select>
                </div>
            </div><br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-primary" />
                <a asp-controller="FaultLogs" asp-action="ViewFaultLogs" asp-route-faultId="@Model.FaultId" class="btn btn-outline-secondary">Back To Fault Logs</a>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/FaultLogs/Index.cshtml
@model IEnumerable<FaultReportingSystem.Models.FaultLog>

@{
    ViewData["Title"] = "Fault Logs";
}
<div class="d-flex justify-content-between align-items-center mb-4">
    <h1>All Fault Logs</h1>
</div><hr />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LogId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FaultId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Action)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Developer)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    Log @Html.DisplayFor(modelItem => item.LogId)
                </td>
                <td>
                    F-@Html.DisplayFor(modelItem => item.Fault.FaultId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Action)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Developer.DeveloperFullNameWithEmail)
                </td>
                <td>
                    <a asp-action="Edit" class="btn btn-outline-primary" asp-route-id="@item.LogId">Edit</a>
                    <a asp-action="Delete" class="btn btn-outline-danger" asp-route-id="@item.LogId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/FaultLogs/ViewFaultLogs.cshtml
@model FaultReportingSystem.Models.Fault

@{
    ViewData["Title"] = "Fault Logs";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string? ActiveUserType = ViewData["LoggedUserType"] as string;
    var FaultLogAddedMessage = TempData["FaultLogAddedMessage"] as string;
    var FaultLogUpdatedMessage = TempData["FaultLogUpdatedMessage"] as string;
    var FaultLogDeletedMessage = TempData["FaultLogDeletedMessage"] as string;
}
@{
    if (ActiveUserType == "Manager" || ActiveUserType == "Developer")
    {
        <div class="d-flex justify-content-between align-items-center mb-4">
            <h1>Fault Logs</h1>
            <a asp-action="Create" asp-controller="FaultLogs" asp-route-faultId="@Model.FaultId" asp-route-developerId="@Model.DeveloperId" class="btn btn-outline-primary">Add Fault Log</a>
        </div>
    }
}
<hr />
@{
    if (!string.IsNullOrEmpty(FaultLogAddedMessage))
    {
        <div class="alert alert-success alert-fade" role="alert">
            @FaultLogAddedMessage
        </div>
    }
    if (!string.IsNullOrEmpty(FaultLogUpdatedMessage))
    {
        <div class="alert alert-success alert-fade" role="alert">
            @FaultLogUpdatedMessage
        </div>
    }
    if (!string.IsNullOrEmpty(FaultLogDeletedMessage))
    {
        <div class="alert alert-success alert-fade" role="alert">
            @FaultLogDeletedMessage
        </div>
    }
}
<div class="row">
    <div class="col-md-6">
        <h5>Fault Information</h5>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4 border-bottom">
                        <span class="text-muted">Fault Id</span>
                    </div>
                    <div class="col-md-8 border-bottom">
                        <span>F-@Model.FaultId</span>
                    </div>

                    <div class="col-md-4 border-bottom">
                        <span class="text-muted">Reported On</span>
                    </div>
                    <div class="col-md-8 border-bottom">
                        <span>@Model.DateReported</span>
                    </div>

                    <div class="col-md-4 border-bottom">
                        <span class="text-muted">Software Product</span>
                    </div>
                    <div class="col-md-8 border-bottom">
                        <span>@Html.DisplayFor(model => model.SoftwareProduct.SoftwareProductIdWithName)</span>
                    </div>

                    <div class="col-md-4 border-bottom">
                        <span class="text-muted">Problem</span>
                    </div>
                    <div class="col-md-8 border-bottom">
                        <span>@Model.Problem</span>
                    </div>

                    <div class="col-md-4 border-bottom">
                        <span class="text-muted">Description</span>
                    </div>
                    <div class="col-md-8 border-bottom">
                        <span>@Model.Description</span>
                    </div>

                    <div class="col-md-4 border-bottom">
                        <span class="text-muted">Fault Type</span>
                    </div>
                    <div class="col-md-8 border-bottom">
                        <span>@Model.FaultType.Replace("_", " ")</span>
                    </div>

                    <div class="col-md-4 border-bottom">
                        <span class="text-muted">Priority</span>
                    </div>
                    <div class="col-md-8 border-bottom">
                        <span>@Model.Priority</span>
                    </div>

                    <div class="col-md-4">
                        <span class="text-muted">Status</span>
                    </div>
                    <div class="col-md-8">
                        <span>@Model.Status.Replace("_", " ")</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-end">
            <a asp-action="Details" asp-controller="Faults" asp-route-id="@Model.FaultId" class="btn btn-outline-secondary">Back</a>
        </div>
    </div>
    <div class="col-md-6">
        <h5>Logs</h5>
        @if (Model.FaultLogs != null && Model.FaultLogs.Any())
        {
            <ul class="list-group">
                @foreach (var log in Model.FaultLogs)
                {
                    <li class="list-group-item border-bottom">
                        <div class="row">
                            <div class="col-md-4">
                                <span class="text-muted">Log Date & Time</span>
                            </div>
                            <div class="col-md-8">
                                <span>@log.DateTime</span>
                            </div>

                            <div class="col-md-4">
                                <span class="text-muted">Action Performed</span>
                            </div>
                            <div class="col-md-8">
                                <span>@log.Action</span>
                            </div>

                            <div class="col-md-4">
                                <span class="text-muted">Developer</span>
                            </div>
                            <div class="col-md-8">
                                <span>
                                    @{
                                        SelectList developersList = ViewBag.Developers;

                                        int? developerId = log.DeveloperId;

                                        var selectedDeveloper = developersList.FirstOrDefault(item => Convert.ToInt32(item.Value) == developerId);

                                        if (selectedDeveloper != null)
                                        {
                                            @selectedDeveloper.Text
                                        }
                                        else if (developerId.HasValue)
                                        {
                                            @developerId
                                        }
                                        else
                                        {
                                        }
                                    }
                                </span>
                            </div>
                        </div>
                        @{
                            if (ActiveUserType == "Manager" || ActiveUserType == "Developer")
                            {
                                <div class="mt-2">
                                    <a asp-action="Edit" asp-route-id="@log.LogId" class="btn btn-sm btn-outline-primary">Edit</a>
                                    <a asp-action="Delete" asp-route-id="@log.LogId" class="btn btn-sm btn-outline-danger ml-2">Delete</a>
                                </div>
                            }
                        }
                    </li>
                }
            </ul>
        }
        else
        {
            <p class="mt-3 text-muted">No fault logs available for this fault.</p>
        }
    </div>
</div>